### ISSUE TITLE
Reformulate text of question "Choose"

### ISSUE THREAD

**Issue by papousek** [adaptive-learning/anatomy-tagging#17]

**Comment by slaweet** [comment]
I don't know how to formulate it so that it is proper English and doesn't take 3 lines.

Now it is:
"Choose levator labii superioris"
I like that it's short - one line with "choose"; second line with the term. The term is set to take up whole line for better visual alignment.
If the term were in the middle of the sentence, it would be at least 3 lines.

I don't like this because you don't click on mobile:
"Click on levator labii superioris"

This doesn't look like proper English:
"Choose in the picture levator labii superioris"

**Comment by marekcierny** [comment]
Identify in the picture levator labii superioris
Find in the picture levator labii superioris

Ale
Identify levator labii superioris in the picture 
Find levator labii superioris in the picture 
zni asi trochu lip.

**Comment by slaweet** [comment]
Fixed by adding a message box to the image saying "The answer can be selected by clicking on the relevant part of the picture."
